export const mockData = [
  {
    id: 1,
    user: "@avi.udash",
    userImage: require("../assets/images/avitypeshit.png"),
    time: "2 mins ago",
    type: "image",
    image: require("../assets/images/skateTest.png"), // Placeholder
    title: "Film around Stanford v1",
    text: "started my film photography arc... here are some shots of @stanford.skates ! hmu if u wanna go shoot tgt around campus sometime",
    comments: 2,
    category: "Visual Arts",
    version: 1,
    projectId: "stanford-film-1", // Unique identifier for the project
  },
  {
    id: 2,
    user: "@Sabzz",
    userImage: require("../assets/images/SabinoCropped.jpeg"), // Placeholder
    time: "2 mins ago",
    type: "audio",
    image: require("../assets/images/splash-icon.png"), // Placeholder
    audio: true, // Placeholder for waveform
    title: "Sabino - Sunrise",
    text: "Been cooking up some new jazz tunes on the sax lately, check it out! 🎷",
    comments: 0,
    category: "Music & Audio",
    version: 1,
    projectId: "sunrise-jazz-1",
  },
  {
    id: 3,
    user: "@adrian",
    userImage: require("../assets/images/andrewTypeShit.png"),
    time: "2 mins ago",
    type: "image",
    image: require("../assets/images/guitarTest.png"), // Placeholder
    title: "Guitar Practice",
    text: "Rehearsing with the band, still figuring out new songs 🎸",
    comments: 2,
    category: "Music & Audio",
    version: 2,
    projectId: "guitar-practice-1",
  },
  {
    id: 4,
    user: "@emma.writer",
    userImage: require("../assets/images/splash-icon.png"),
    time: "1 hour ago",
    type: "text",
    image: require("../assets/images/splash-icon.png"),
    title: "The Last Chapter - Draft 3",
    text: "Finally finished the third draft of my novel's final chapter. Would love some feedback on the character development! 📚",
    comments: 5,
    category: "Writing & Language",
    version: 3,
    projectId: "novel-final-chapter",
  },
  {
    id: 5,
    user: "@dance.maya",
    userImage: require("../assets/images/splash-icon.png"),
    time: "3 hours ago",
    type: "video",
    image: require("../assets/images/splash-icon.png"),
    title: "Contemporary Dance Piece - Rehearsal",
    text: "Working on the new choreography for our upcoming performance. This is the second iteration of the main sequence. 💃",
    comments: 3,
    category: "Performance",
    version: 2,
    projectId: "contemporary-dance-2024",
  },
  {
    id: 6,
    user: "@avi.udash",
    userImage: require("../assets/images/avitypeshit.png"),
    time: "5 hours ago",
    type: "image",
    image: require("../assets/images/skateTest.png"),
    title: "Film around Stanford v2",
    text: "Second batch of photos from my film photography session. Added some new angles and lighting techniques! 📸",
    comments: 4,
    category: "Visual Arts",
    version: 2,
    projectId: "stanford-film-1",
  },
  {
    id: 7,
    user: "@jazz.collective",
    userImage: require("../assets/images/splash-icon.png"),
    time: "1 day ago",
    type: "audio",
    image: require("../assets/images/splash-icon.png"),
    audio: true,
    title: "Jazz Collective - Live Session",
    text: "Our first live recording session! Still working on the mix, but the energy was incredible. 🎺",
    comments: 8,
    category: "Music & Audio",
    version: 1,
    projectId: "jazz-collective-live",
  },
  {
    id: 8,
    user: "@poet.sarah",
    userImage: require("../assets/images/splash-icon.png"),
    time: "2 days ago",
    type: "text",
    image: require("../assets/images/splash-icon.png"),
    title: "Urban Echoes - Poem Collection",
    text: "Sharing the first draft of my new poem collection. Would love to hear your thoughts on the imagery and rhythm. ✍️",
    comments: 6,
    category: "Writing & Language",
    version: 1,
    projectId: "urban-echoes-poems",
  },
  {
    id: 9,
    user: "@dance.maya",
    userImage: require("../assets/images/splash-icon.png"),
    time: "2 days ago",
    type: "video",
    image: require("../assets/images/splash-icon.png"),
    title: "Contemporary Dance Piece - Concept",
    text: "Initial concept video for our new piece. Still working on the transitions and emotional flow. 🎭",
    comments: 2,
    category: "Performance",
    version: 1,
    projectId: "contemporary-dance-2024",
  },
  {
    id: 10,
    user: "@Sabzz",
    userImage: require("../assets/images/SabinoCropped.jpeg"),
    time: "3 days ago",
    type: "audio",
    image: require("../assets/images/splash-icon.png"),
    audio: true,
    title: "Sabino - Sunrise (Remix)",
    text: "Experimenting with some new electronic elements in the remix. Let me know what you think! 🎵",
    comments: 4,
    category: "Music & Audio",
    version: 2,
    projectId: "sunrise-jazz-1",
  },
];
